/**
 * Dynamic block — saves no markup to post_content at all. The actual
 * content is entirely generated by render.php when the page is
 * requested, so the table of contents always reflects the article's
 * CURRENT headings.
 */

export default function save() {
	return null;
}
