<?php
/**
 * Builds the Tabs block frontend markup from its child "tabs-item" blocks.
 *
 * @package GameStuff
 */

namespace GameStuff\Blocks\Tabs;

/**
 * Reads inner "gamestuff/tabs-item" blocks directly from block data and
 * assembles the nav + panels markup. The children never render their own
 * label or wrapper — this class is the single source of truth for both,
 * since the id/aria relationships between a tab and its panel depend on
 * the item's position among its siblings, which is only known here.
 */
class TabsRenderer {

	/**
	 * Render the Tabs block.
	 *
	 * @param array     $attributes Block attributes.
	 * @param \WP_Block $block      Block instance, used to read parsed inner blocks.
	 * @return string
	 */
	public static function render( array $attributes, \WP_Block $block ) {
		$items = self::get_tab_items( $block );

		if ( empty( $items ) ) {
			return '';
		}

		$style       = 'sidebar' === ( $attributes['style'] ?? '' ) ? 'sidebar' : 'underline';
		$orientation = 'sidebar' === $style ? 'vertical' : 'horizontal';
		$unique_id   = wp_unique_id( 'gsb-tabs-' );

		$nav_html    = '';
		$panels_html = '';

		foreach ( $items as $index => $item ) {
			$is_active = 0 === $index;
			$tab_id    = sprintf( '%s-tab-%d-label', $unique_id, $index );
			$panel_id  = sprintf( '%s-tab-%d-panel', $unique_id, $index );
			$label     = self::get_label( $item, $index );

			$nav_html .= sprintf(
				'<button type="button" class="gsb-tabs__tab%s" id="%s" role="tab" aria-selected="%s" aria-controls="%s" tabindex="%s">%s</button>',
				$is_active ? ' is-active' : '',
				esc_attr( $tab_id ),
				$is_active ? 'true' : 'false',
				esc_attr( $panel_id ),
				$is_active ? '0' : '-1',
				wp_kses_post( $label )
			);

			$panels_html .= sprintf(
				'<div class="gsb-tabs__panel%s" id="%s" role="tabpanel" aria-labelledby="%s"%s>%s</div>',
				$is_active ? ' is-active' : '',
				esc_attr( $panel_id ),
				esc_attr( $tab_id ),
				$is_active ? '' : ' hidden',
				render_block( $item ) // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- rendered via core block rendering, each block escapes its own output.
			);
		}

		$wrapper_attributes = get_block_wrapper_attributes(
			array(
				'class'      => 'gsb-tabs',
				'data-style' => $style,
			)
		);

		return sprintf(
			'<div %1$s><div class="gsb-tabs__nav" role="tablist" aria-orientation="%2$s">%3$s</div><div class="gsb-tabs__panels">%4$s</div></div>',
			$wrapper_attributes, // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- generated by WordPress core, already escaped.
			esc_attr( $orientation ),
			$nav_html, // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- individually escaped above.
			$panels_html // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- individually escaped above.
		);
	}

	/**
	 * Filter parsed inner blocks down to actual tab items, ignoring
	 * anything unexpected (e.g. leftover markup from a corrupted save).
	 *
	 * @param \WP_Block $block Block instance.
	 * @return array
	 */
	private static function get_tab_items( \WP_Block $block ) {
		$inner_blocks = $block->parsed_block['innerBlocks'] ?? array();

		return array_values(
			array_filter(
				$inner_blocks,
				static function ( $inner_block ) {
					return 'gamestuff/tabs-item' === ( $inner_block['blockName'] ?? '' );
				}
			)
		);
	}

	/**
	 * Get a tab's label, falling back to a numbered default when the
	 * item was saved with an empty label.
	 *
	 * @param array $item  Parsed tab item block.
	 * @param int   $index Zero-based position among its siblings.
	 * @return string
	 */
	private static function get_label( array $item, $index ) {
		$label = trim( $item['attrs']['label'] ?? '' );

		if ( '' === $label ) {
			/* translators: %d: tab position, starting at 1. */
			$label = sprintf( __( 'Tab %d', 'gamestuff-blocks' ), $index + 1 );
		}

		return $label;
	}
}